### ISSUE TITLE
RE: Selenium Support

### ISSUE THREAD

**Issue by momer** [xautlx/nutch-ajax#2]
Hey @xautlx - One of my selenium plugins (hopefully both) have been/are being merged into Nutch trunk at the moment. Check out https://github.com/momer/nutch-selenium , https://github.com/momer/nutch-selenium-grid-plugin and the JIRA issue at https://issues.apache.org/jira/browse/NUTCH-1933 for more info. Figured I'd pass this along since I saw Selenium Firefox in here as well!

**Comment by xautlx** [comment]
Thanks sharing. I have just looked at your project code, and fount a small issue: 

String innerHtml = driver.findElement(By.tagName("body")).getAttribute("innerHTML");

Your implement just return "body" content to Nutch and discard "header" content that maybe useful for the following Parse step. 

My way is: 

String html = driver.getPageSource()

**Comment by momer** [comment]
Yeah, my implementation was pretty use-case specific, but the one implemented in Nutch now (see the JIRA issue) is much more flexible as to which tag's content you pull in. That's a good idea, though; I'll make a comment to consider adding a config option like `content_selection` which could be either 'ALL' or a specific tag like 'body'. This would allow for a conditional use of getPageSource(), while also allowing the retrieval of specific html tags.

**Comment by momer** [comment]
Added a comment in JIRA @ https://issues.apache.org/jira/browse/NUTCH-1948

**Comment by momer** [comment]
Side note: guess I'd removed that at some point - the repos originally used getPageSource https://github.com/momer/nutch-selenium-grid-plugin/commit/a3745ac685078f0c26fda821aa5fbdf2a3994d41#
