### ISSUE TITLE
git clone源码后 在nutch-ajax/apache-nutch-2.3目录下ant clean，ant 后报错误,

### ISSUE THREAD

**Issue by LQZYC** [xautlx/nutch-ajax#4]
compile:
     [echo] Compiling plugin: parse-s2jh
    [javac] Compiling 7 source files to /home/lq/nutch-ajax/apache-nutch-2.3/build/parse-s2jh/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] /home/lq/nutch-ajax/apache-nutch-2.3/src/plugin/parse-s2jh/src/java/org/apache/nutch/parse/s2jh/AbstractHtmlParseFilter.java:38: error: package org.apache.nutch.protocol.htmlunit does not exist
    [javac] import org.apache.nutch.protocol.htmlunit.HttpWebClient;
    [javac]                                          ^
    [javac] /home/lq/nutch-ajax/apache-nutch-2.3/src/plugin/parse-s2jh/src/java/org/apache/nutch/parse/s2jh/AbstractHtmlParseFilter.java:61: warning: XPathAPI is internal proprietary API and may be removed in a future release
    [javac] import com.sun.org.apache.xpath.internal.XPathAPI;
    [javac]                                         ^
    [javac] /home/lq/nutch-ajax/apache-nutch-2.3/src/plugin/parse-s2jh/src/java/org/apache/nutch/parse/s2jh/AbstractHtmlParseFilter.java:120: warning: XPathAPI is internal proprietary API and may be removed in a future release
    [javac]             return XPathAPI.selectNodeList(node, xpath);
    [javac]                    ^
    [javac] /home/lq/nutch-ajax/apache-nutch-2.3/src/plugin/parse-s2jh/src/java/org/apache/nutch/parse/s2jh/AbstractHtmlParseFilter.java:135: warning: XPathAPI is internal proprietary API and may be removed in a future release
    [javac]             return XPathAPI.selectSingleNode(contextNode, xpath);
    [javac]                    ^
    [javac] /home/lq/nutch-ajax/apache-nutch-2.3/src/plugin/parse-s2jh/src/java/org/apache/nutch/parse/s2jh/AbstractHtmlParseFilter.java:317: warning: XPathAPI is internal proprietary API and may be removed in a future release
    [javac]             NodeList nodes = XPathAPI.selectNodeList(node, xpath);
    [javac]                              ^
    [javac] /home/lq/nutch-ajax/apache-nutch-2.3/src/plugin/parse-s2jh/src/java/org/apache/nutch/parse/s2jh/AbstractHtmlParseFilter.java:425: error: cannot find symbol
    [javac]                     Page imgPage = HttpWebClient.getPage(imgSrc, getConf());
    [javac]                                    ^
    [javac]   symbol:   variable HttpWebClient
    [javac]   location: class AbstractHtmlParseFilter
    [javac] 2 errors
    [javac] 5 warnings

BUILD FAILED
/home/lq/nutch-ajax/apache-nutch-2.3/build.xml:113: The following error occurred while executing this line:
/home/lq/nutch-ajax/apache-nutch-2.3/src/plugin/build.xml:73: The following error occurred while executing this line:
/home/lq/nutch-ajax/apache-nutch-2.3/src/plugin/build-plugin.xml:117: Compile failed; see the compiler error output for details.

**Comment by xautlx** [comment]
Fixed
